export default {
  total: 10,
  rows: [
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 1,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 2,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 3,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 4,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 5,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 6,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 7,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 8,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 9,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
    {
      searchValue: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      remark: null,
      params: {},
      friendId: 10,
      friendName: '图层云',
      friendUrl: 'https://tucengyun.com/',
      friendInfo:
        '专注于海外精品AE模板、各种最新AE插件，PR模板、PR插件、转场预设、视频素材、音频素材。LR调色预设、LUT调色预设等资源，提供海外平面资源下载。',
      friendPic: 'https://pic.imgdb.cn/item/61f903e32ab3f51d91d313c9.png',
      friendType: null,
      friendStatus: null,
    },
  ],
  code: 200,
  msg: '查询成功',
};
